import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {CHARACTERS,pathSamples,ZONES} from '../shared/core.js';
const evidence=new URL('../docs/screenshots/',import.meta.url);await mkdir(evidence,{recursive:true});const browser=await chromium.launch({headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const context=await browser.newContext({viewport:{width:1194,height:834},serviceWorkers:'block',permissions:['camera']});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:4173';const log=[];const pass=s=>{log.push(s);console.log('PASS',s);};
const shot=async name=>page.screenshot({path:new URL(name+'.png',evidence).pathname,fullPage:true});
async function pick(item,target='dino'){await page.locator(`[data-item="${item}"]:not(.used)`).first().click();await page.locator(`[data-target="${target}"]`).click();}
async function next(){await page.locator('#next-round').click();}
async function enter(id){await page.goto(base+'/hub/#/play/'+id);await page.locator('#game').waitFor();}
try{
 await page.goto(base+'/hub/');await page.locator('#nickname').fill('小晴');await shot('welcome');await page.getByRole('button',{name:'出發去島上'}).click();await page.locator('.stone').first().waitFor();assert.equal(await page.locator('.stone').count(),11);await shot('map');pass('Welcome creates participant; island has 11 freely selectable stones');
 await page.goto(base+'/hub/#/cert');await page.waitForURL('**/#/map');pass('Certificate direct route denied below 6 stations');
 for(const id of ['english','mandarin']){await enter(id);for(const item of id==='english'?['water','apple','sleep']:['umbrella','apple','sleep']){if(id==='english')assert(!/[a-zA-Z]/.test(await page.locator('#app').innerText()));if(id==='mandarin')assert.equal((await page.locator('.choices').innerText()).trim(),'');await pick(item);await next();}await page.locator('#return-map').waitFor();pass(id+' playable with images only, text restriction intact');}
 await enter('math');for(const n of [1,3,5]){await pick('leaf');assert.equal(await page.locator('#next-round').count(),0);for(let i=0;i<n;i++)await pick('apple');await next();}await page.locator('#return-map').waitFor();pass('Math requires each apple, wrong food does not advance');
 await enter('general');await pick('hat');await pick('water');await next();await pick('umbrella');await next();await pick('coat');await next();pass('Weather requires both hat and water, then umbrella and coat');
 await enter('science');for(let i=0;i<3;i++){let sc=await page.evaluate(()=>JSON.parse(localStorage.getItem('dino-island-20260913:player')).zones.science.game.scenarios);const item={thirst:'water',hungry:'apple',tired:'sleep',mud:'bath'}[sc[i]];await pick(item);assert.equal(await page.locator('#next-round').count(),0);await page.locator('.need').click();await pick(item);await next();}pass('Science requires observing clue before treatment');
 await enter('humanities');await pick('apple');await next();await pick('apple','child');await pick('apple');await next();pass('Sharing and turn taking complete with only one baby dino');
 await page.goto(base+'/hub/#/cert');await page.waitForFunction(()=>document.querySelector('.cert-preview')?.naturalWidth===1600,{timeout:10000});await shot('certificate');pass('Six completions unlock real 1600px certificate image');
 await enter('computing');await pick('leaf');assert.equal(await page.locator('#next-round').count(),0);await pick('water');await next();await pick('leaf');assert.equal(await page.locator('#next-round').count(),0);await pick('water');await pick('leaf');await next();pass('Computing enforces water then leaf, maximum 2 steps');
 await enter('chinese');for(const c of CHARACTERS){for(const path of c.paths){const box=await page.locator('.trace-board').boundingBox(),points=pathSamples(path,5);await page.mouse.move(box.x+points[0][0]/300*box.width,box.y+points[0][1]/300*box.height);await page.mouse.down();for(const p of points.slice(1))await page.mouse.move(box.x+p[0]/300*box.width,box.y+p[1]/300*box.height);await page.mouse.up();}await next();}pass('All 山水木 strokes traced successfully through pointer input');
 await enter('art');for(const shape of ['circle','square','triangle']){const b=await page.locator('.paint-stone').boundingBox();await page.mouse.move(b.x+15,b.y+15);await page.mouse.down();for(let row=0;row<3;row++)for(let col=0;col<3;col++)await page.mouse.move(b.x+(col+.5)*b.width/5,b.y+(row+.5)*b.height/5);await page.mouse.up();await pick(shape,'bridge');await next();}pass('Art requires finger painting then matching 3 shapes');
 await enter('music');for(const seq of [[0,1],[1,0],[0,2,1]]){await page.waitForFunction(()=>document.querySelector('[data-drum]')&&!document.querySelector('[data-drum]').disabled);for(const i of seq)await page.locator(`[data-drum="${i}"]`).click();await next();}pass('Music light sequences playable without audio');
 await page.locator('#return-map').click();await page.locator('.stone.done').first().waitFor();assert.equal(await page.locator('.stone.done').count(),10);assert.equal(await page.locator('.stone:disabled').count(),11);assert(await page.locator('[data-zone="pe"]').isDisabled());assert((await page.locator('.map-progress').innerText()).includes('10 分滿分'));await shot('map-complete');pass('Any 10 stations reach full score; the unchosen 11th station locks');
 const first=await page.evaluate(()=>JSON.parse(localStorage.getItem('dino-island-20260913:player')));await page.goto(base+'/hub/#/play/computing');await page.waitForURL('**/#/map');assert(await page.locator('[data-zone=computing]').isDisabled());const replay=await page.evaluate(()=>JSON.parse(localStorage.getItem('dino-island-20260913:player')));assert.equal(replay.version,first.version);assert.equal(replay.zones.computing.ms,first.zones.computing.ms);pass('Completed station locked through map and direct route');
 await page.goto(base+'/hub/#/cert');await page.locator('#camera-start').click();await page.waitForFunction(()=>document.querySelector('video').videoWidth>0);await page.locator('#shutter').click();await page.waitForFunction(()=>!document.querySelector('#photo-actions').classList.contains('hidden'));await page.waitForTimeout(400);assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('dino-island-20260913:photoPending'))));await shot('photo-certificate');await page.locator('#upload').click();assert.equal(await page.locator('#qr svg').count(),0);pass('Camera captures; no download QR fabricated when Google is unconfigured');
 await page.locator('#next-player').click();assert((await page.locator('dialog').innerText()).includes('放棄'));await page.locator('#stay').click();await page.locator('#discard').click();await page.waitForTimeout(100);await page.locator('#next-player').click();await page.locator('#reset').click();await page.locator('#nickname').waitFor();pass('Next participant confirmation clears active progress and private pending photo');
 await page.setViewportSize({width:390,height:844});await shot('mobile-welcome');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('Phone welcome has no horizontal overflow');
 await page.setViewportSize({width:1920,height:1080});await page.goto(base+'/board/');await page.evaluate(()=>{const p={};for(let i=0;i<12;i++)p['test'+i]={id:'test'+i,name:i===0?'一二三四五六七八':'小探險家'+i,zonesCompleted:10,zoneIds:['chinese','english','mandarin','math','general','science','humanities','art','music','computing'],totalMs:123000+i*1000,certReady:true,reachedAt:i};localStorage.setItem('dino-island-20260913:localBoard',JSON.stringify(p));});await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.board-row').length===10);await shot('board');assert((await page.locator('#others').innerText()).includes('2'));assert((await page.locator('.station-count').first().innerText()).includes('10'));assert(await page.evaluate(()=>document.querySelector('.board').getBoundingClientRect().bottom<=1081));pass('TV ranks 10-point explorers by total time with one of 11 stations unchosen');
 assert.deepEqual(errors,[]);pass('No browser runtime errors');
}catch(e){console.error(e);await shot('failure');process.exitCode=1;}finally{await writeFile(new URL('../docs/browser-test-results.json',import.meta.url),JSON.stringify({testedAt:new Date().toISOString(),browser:'Chromium desktop with iPad-like viewport; not physical iPad',passed:log,errors},null,2));await browser.close();}
