import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1024,height:768},serviceWorkers:'block'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base='http://127.0.0.1:4173';await page.goto(base+'/hub/?demo=1#/map');await page.locator('[data-zone]').first().waitFor();assert.equal(await page.locator('[data-zone]').count(),11);assert.equal(await page.locator('.map-school').innerText(),'佛教志蓮小學');assert.equal(await page.locator('.map-header h2').innerText(),'智取恐龍島');assert.equal(await page.locator('.map-island .park-guides img').count(),2);
await page.waitForFunction(()=>[...document.images].every(i=>i.complete));
for(const size of [{width:1024,height:768},{width:1194,height:834}]){await page.setViewportSize(size);const rects=await page.locator('[data-zone]').evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return {id:e.dataset.zone,x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom};}));for(const r of rects){assert(r.w>=64&&r.h>=64,`${r.id} target >=64px`);assert(r.x>=0&&r.y>=0&&r.right<=size.width&&r.bottom<=size.height,`${r.id} within iPad viewport`);}for(const r of rects){const hit=await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.closest('[data-zone]')?.dataset.zone,{x:r.x+r.w/2,y:r.y+r.h/2});assert.equal(hit,r.id,'habitat center hit');}await page.screenshot({path:new URL(`../docs/screenshots/park-map-${size.width}.png`,import.meta.url).pathname,fullPage:true});}
// Any park can be first: visit last, then first, then a middle subject.
for(const id of ['computing','chinese','science']){const before=await page.locator('.park-guides').getAttribute('style');await page.locator(`[data-zone="${id}"]`).click();assert(page.url().endsWith('#/map'),'walk before entering game');await page.waitForTimeout(350);assert.notEqual(await page.locator('.park-guides').getAttribute('style'),before,'guides move along map');assert.equal(await page.locator('#game').count(),0,'no game timer during walk');await page.locator('[data-zone="english"]').click();await page.locator('#game').waitFor();assert(page.url().endsWith('/play/'+id));await page.locator('#back-map').click();await page.locator('[data-zone]').first().waitFor();}
// Returning to the same unfinished park remains valid; reduced motion avoids stepping.
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-zone="science"]').click();await page.locator('#game').waitFor();await page.locator('#back-map').click();await page.locator('.park-guides').waitFor();assert(!(await page.locator('.park-guides').getAttribute('style')).includes('NaN'));await page.emulateMedia({reducedMotion:'no-preference'});
// Leaving mid-walk cancels the pending game navigation.
await page.locator('[data-zone="math"]').click();await page.evaluate(()=>location.hash='/cert');await page.waitForURL(u=>u.hash==='#/map');await page.waitForTimeout(3400);assert.equal(await page.locator('#game').count(),0);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:new URL('../docs/screenshots/park-map-phone.png',import.meta.url).pathname,fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'phone page must not overflow');
await page.setViewportSize({width:1024,height:768});await page.evaluate(()=>{const key='dino-island-demo:player';let p=JSON.parse(localStorage.getItem(key));for(const id of ['chinese','english','mandarin','math','general','science'])p.zones[id]={complete:true,ms:1000};localStorage.setItem(key,JSON.stringify(p));});await page.reload();await page.locator('[data-zone]').first().waitFor();assert.equal(await page.locator('[data-zone]:disabled').count(),6);assert(await page.locator('#certificate').isVisible());await page.goto(base+'/hub/?demo=1#/play/chinese');await page.waitForURL(u=>u.hash==='#/map');assert.equal(await page.locator('#game').count(),0);
assert.deepEqual(errors,[]);const report={testedAt:new Date().toISOString(),environment:'Chromium iPad-sized viewports; not physical iPad',passed:['11 distinct selectable park targets','All habitats fit 1024x768 and 1194x834 with >=64px targets','Habitat centers route to correct subject','Any order with animated guides, delayed game entry and double-tap protection','Phone scroll layout without page overflow','Completed parks disabled and direct route guarded','Six completions unlock certificate','No runtime errors']};await writeFile(new URL('../docs/park-map-test-results.json',import.meta.url),JSON.stringify(report,null,2));await browser.close();console.log('PASS park map layout, free routes, touch targets, locks and six-station certificate');
