import {test} from 'node:test';import assert from 'node:assert/strict';import {PoseActions} from '../shared/pose-actions.js';
function person(){const p=Array.from({length:33},()=>({x:.5,y:.3,visibility:1,presence:1}));for(const [i,x,y]of [[0,.5,.1],[11,.43,.3],[12,.57,.3],[15,.35,.52],[16,.65,.52],[23,.45,.5],[24,.55,.5],[25,.45,.7],[26,.55,.7],[27,.45,.9],[28,.55,.9]])Object.assign(p[i],{x,y});return p;}
function fixture(){const a=new PoseActions();let t=0;const update=p=>a.update(p,t+=100);for(let i=0;i<11;i++)update([person()]);assert(a.baseline);return {a,update,hold:p=>{let r;for(let i=0;i<17;i++)r=update([p]);return r;}};}
const moved=(dx,dy=0)=>person().map(p=>({...p,x:p.x+dx,y:p.y+dy}));
test('Calibration requires one confident, full body standing still for a second',()=>{const a=new PoseActions(),p=person();assert.equal(a.update([],0).status,'no-person');assert.equal(a.update([p,p],100).status,'multiple');p[27].visibility=.2;assert.equal(a.update([p],200).status,'unclear');assert.equal(a.baseline,null);const s=fixture();assert.equal(s.update([person()]).status,'ready');});
test('Hands need both wrists up and a sustained hold',()=>{const s=fixture();s.a.setCommand('hands');const p=person();p[15].y=.12;assert.notEqual(s.hold(p).status,'success');p[16].y=.12;assert.notEqual(s.update([p]).status,'success');assert.equal(s.hold(p).status,'success');});
test('Mirrored left and right reject the opposite direction',()=>{for(const [command,dx]of [['left',.15],['right',-.15]]){const s=fixture();s.a.setCommand(command);assert.notEqual(s.hold(moved(-dx)).status,'success');assert.equal(s.hold(moved(dx)).status,'success');}});
test('Squat needs bent knees and lowered hips; standing is distinct',()=>{const s=fixture();s.a.setCommand('sit');assert.notEqual(s.hold(person()).status,'success');const p=person();for(const i of [23,24])p[i].y=.73;for(const i of [25,26]){p[i].x+=.1;p[i].y=.76;}assert.equal(s.hold(p).status,'success');s.a.setCommand('stand');assert.notEqual(s.hold(p).status,'success');assert.equal(s.hold(person()).status,'success');});
test('Freeze compares to an anchor, so slow drift cannot count as still',()=>{const s=fixture();s.a.setCommand('freeze');let r;for(let i=0;i<16;i++)r=s.update([moved(i*.009)]);assert.notEqual(r.status,'success');assert.equal(s.hold(person()).status,'success');});
test('Jump requires upward feet and hips, then landing; crouching does not pass',()=>{const s=fixture();s.a.setCommand('jump');assert.notEqual(s.hold(person()).status,'success');const air=moved(0,-.08);assert.notEqual(s.update([air]).status,'success');assert.notEqual(s.update([air]).status,'success');assert.equal(s.update([person()]).status,'success');});
test('Missing confidence, multiple people and frame gaps reset pending holds',()=>{const s=fixture();s.a.setCommand('stand');s.update([person()]);s.update([person()]);s.update([]);assert.equal(s.update([person()]).progress,0);s.update([person(),person()]);assert.equal(s.update([person()]).progress,0);assert.equal(s.a.update([person()],100000).progress,0);});
