import {icon} from '../../shared/icons.js';
const palette=[['#146b4d','森綠'],['#e5bc5d','金黃'],['#ee937c','珊瑚紅'],['#7fc9db','天藍'],['#a699cd','紫色'],['#f6f3ec','奶油白'],['#efab65','橙色']];
const shapes={circle:'<circle r="22"/>',square:'<rect x="-21" y="-21" width="42" height="42" rx="3"/>',triangle:'<path d="M0-25L25 20H-25Z"/>',heart:'<path d="M0 23C-50-6-18-39 0-17C18-39 50-6 0 23Z"/>'};
const patterns={dots:'<circle cx="-12" cy="-12" r="6"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="-12" r="6"/><circle cx="-12" cy="12" r="6"/>',stripes:'<path d="M-22-18H22M-22 0H22M-22 18H22" fill="none" stroke="currentColor" stroke-width="7"/>',waves:'<path d="M-24-12q12-16 24 0t24 0M-24 12q12-16 24 0t24 0" fill="none" stroke="currentColor" stroke-width="6"/>',zigzag:'<path d="M-24-18L-8-4L8-18L24-4M-24 6L-8 20L8 6L24 20" fill="none" stroke="currentColor" stroke-width="6"/>'};
const stamps={star:'<path d="M0-25L7-8L25-6L12 7L15 25L0 16L-15 25L-12 7L-25-6L-7-8Z"/>',leaf:'<path d="M-20 22Q-30-30 24-23Q30 29-20 22Z"/>',flower:'<circle cx="0" cy="-14" r="11"/><circle cx="14" cy="0" r="11"/><circle cx="0" cy="14" r="11"/><circle cx="-14" cy="0" r="11"/><circle r="7" fill="#f6f3ec"/>',footprint:'<ellipse cy="10" rx="14" ry="12"/><ellipse cx="-15" cy="-10" rx="6" ry="8"/><ellipse cy="-17" rx="6" ry="8"/><ellipse cx="15" cy="-10" rx="6" ry="8"/>'};
shapes.star=stamps.star;
stamps.volcano='<path d="M-26 24L-9-10H9L26 24Z"/><path d="M-8-16Q-16-25-7-29M7-16Q15-25 6-29" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>';
// Keep earlier saved white, heart and flower marks renderable; offer the requested tools.
const toolIds={shape:['circle','triangle','square','star'],pattern:Object.keys(patterns),stamp:['footprint','leaf','volcano','star']};
const labels={circle:'圓形',square:'正方形',triangle:'三角形',volcano:'火山',heart:'心形',dots:'圓點',stripes:'橫紋',waves:'波浪',zigzag:'鋸齒紋',star:'星星',leaf:'葉子',flower:'花朵',footprint:'龍腳印'};
const eggPath='M150 15C91 15 35 123 35 197C35 308 265 308 265 197C265 123 209 15 150 15Z';
const glyph=(type,id)=>({shape:shapes,pattern:patterns,stamp:stamps}[type]?.[id]||'');
const preview=(type,id)=>`<svg viewBox="-32 -32 64 64" aria-hidden="true" fill="currentColor">${glyph(type,id)}</svg>`;
function markSVG(mark){const color=palette[mark.color]?.[0]||palette[0][0];return mark.type==='brush'?`<polyline points="${mark.points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/>`:`<g transform="translate(${mark.x} ${mark.y})" fill="${color}" color="${color}">${glyph(mark.type,mark.item)}</g>`;}
export function mountArt(root,state,save,finish){
 state.marks??=[];state.color??=0;state.mode??='brush';state.item??='circle';state.hatched??=false;
 let live=true,pointer=null,pending=null,timer=null,animating=false;
 function cancel(){pointer=null;pending=null;root.querySelector('#art-pending')?.replaceChildren();}
 function render(){
  cancel();root.innerHTML=`<h2 class="game-instruction">彩蛋創作室</h2><p class="game-instruction">${state.hatched?'你嘅彩蛋孵出小龍啦！':'揀顏色，用手指畫一畫，再加形狀、紋樣同印章。'}</p><div class="egg-studio"><img class="character egg-guide" src="img/chars/xiaolian-color.png" alt="小蓮陪你裝飾彩蛋"><div class="egg-artwork ${state.hatched?'has-hatched':''}">${state.hatched?'<img class="character hatch-dino" src="img/games/art/dino-hatching.png" alt="彩蛋孵出開心小龍">':''}<svg id="egg-canvas" viewBox="0 0 300 310" role="img" aria-label="手指裝飾恐龍蛋"><defs><clipPath id="egg-clip"><path d="${eggPath}"/></clipPath></defs><path id="egg-surface" d="${eggPath}" fill="#fff8df"/><g clip-path="url(#egg-clip)"><g id="art-marks">${state.marks.map(markSVG).join('')}</g><g id="art-pending"></g></g><path d="${eggPath}" fill="none" stroke="#203b2e" stroke-width="5"/><path class="egg-crack" d="M48 153L87 174L125 149L163 177L206 148L253 169" fill="none" stroke="#203b2e" stroke-width="6"/></svg></div><img class="character egg-guide ${state.hatched?'is-surprised':''}" src="img/${state.hatched?'games/art/xiaozhi-surprised':'chars/xiaozhi-highfive'}.png" alt="${state.hatched?'小志驚喜迎接小龍':'小志期待小龍出蛋'}"></div>${state.hatched?'<p class="feedback" role="status">你用顏色同圖案歡迎新生命，小龍開心同你打招呼！</p><div class="actions"><button class="primary" id="art-finish">完成照顧任務</button></div>':`<div class="art-colors" aria-label="六色畫具">${[2,1,3,0,4,6].map(i=>{const [color,label]=palette[i];return `<button data-art-color="${i}" aria-label="${label}" aria-pressed="${i===state.color}" style="background:${color}">${i===state.color?'✓':''}</button>`;}).join('')}</div><div class="actions art-modes">${[['brush','畫筆'],['shape','形狀'],['pattern','紋樣'],['stamp','印章']].map(([id,label])=>`<button data-art-mode="${id}" aria-pressed="${state.mode===id}">${id==='brush'?icon('paint'):preview(id,toolIds[id][0])}${label}</button>`).join('')}</div><div class="art-tools">${state.mode==='brush'?'<p>手指按住蛋殼，慢慢畫。</p>':toolIds[state.mode].map(id=>`<button data-art-item="${id}" aria-label="${labels[id]}" aria-pressed="${state.item===id}">${preview(state.mode,id)}<span>${labels[id]}</span></button>`).join('')}</div><p class="feedback" role="status">自由揀顏色，冇標準答案。至少畫一筆，再同小龍打招呼。</p><div class="actions"><button id="art-undo" ${state.marks.length?'':'disabled'}>復原一筆</button><button id="art-clear" ${state.marks.length?'':'disabled'}>清除全部</button><button class="primary" id="art-hatch" ${state.marks.length?'':'disabled'}>彩蛋孵化</button></div>`}`;
  if(state.hatched){root.querySelector('#art-finish').onclick=()=>{if(live){live=false;finish();}};return;}
  root.querySelectorAll('[data-art-color]').forEach(b=>b.onclick=()=>{state.color=Number(b.dataset.artColor);save();render();});
  root.querySelectorAll('[data-art-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.artMode;state.item=state.mode==='brush'?'':toolIds[state.mode][0];save();render();});
  root.querySelectorAll('[data-art-item]').forEach(b=>b.onclick=()=>{state.item=b.dataset.artItem;save();render();});
  root.querySelector('#art-undo').onclick=()=>{state.marks.pop();save();render();};
  root.querySelector('#art-clear').onclick=()=>{state.marks=[];save();render();};
  root.querySelector('#art-hatch').onclick=()=>{if(!state.marks.length||animating)return;animating=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);root.querySelector('.egg-artwork').classList.add('is-hatching');root.querySelector('.feedback').textContent='彩蛋搖一搖，小龍準備出嚟啦！';timer=setTimeout(()=>{if(!live)return;animating=false;state.hatched=true;save();render();},2400);};
  const svg=root.querySelector('#egg-canvas'),surface=root.querySelector('#egg-surface');
  const position=e=>{const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());return [Math.round(point.x),Math.round(point.y)];};
  const paint=()=>{root.querySelector('#art-pending').innerHTML=markSVG(pending);};
  svg.onpointerdown=e=>{if(animating||pointer!==null||e.button!==0)return;const p=position(e);if(!surface.isPointInFill(new DOMPoint(...p)))return;pointer=e.pointerId;svg.setPointerCapture(pointer);pending=state.mode==='brush'?{type:'brush',color:state.color,points:[p,p]}:{type:state.mode,item:state.item,color:state.color,x:p[0],y:p[1]};paint();};
  svg.onpointermove=e=>{if(e.pointerId!==pointer||!pending)return;if(pending.type==='brush'){const p=position(e),last=pending.points.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])>3){pending.points.push(p);paint();}}};
  svg.onpointerup=e=>{if(e.pointerId!==pointer||!pending)return;state.marks.push(pending);save();render();};
  svg.onpointercancel=()=>cancel();
 }
 const background=()=>{if(document.hidden){cancel();if(animating){clearTimeout(timer);animating=false;render();}}};
 document.addEventListener('visibilitychange',background);render();return()=>{live=false;cancel();clearTimeout(timer);document.removeEventListener('visibilitychange',background);};
}
