import {hintLevel} from '../../shared/game-state.js';
const parts=['head','body','legs','tail'];
const names={head:'頭骨',body:'身體',legs:'腳骨',tail:'尾骨'};
const bones={head:'<path d="M80 63H28Q8 63 8 46V30Q8 12 30 12H65Q82 12 82 30V47H96V63Z"/><circle cx="33" cy="31" r="10" fill="#b49a70"/><path d="M15 70H80V83H24ZM60 25h7"/>',body:'<path d="M4 23H96V34H4Z"/><path d="M20 32Q3 80 39 85M40 32Q27 80 49 85M60 32Q76 80 54 85M80 32Q97 78 67 84" fill="none" stroke-width="9"/>',legs:'<path d="M21 8L37 42L29 79H49V92H12V77L21 44L8 16ZM64 8L79 44L73 79H93V92H57V77L64 44L51 16Z"/>',tail:'<path d="M4 29Q43 39 94 76Q47 68 4 52Z"/><path d="M26 35L23 57M46 44L43 62M65 56L61 67"/>'};
const fossil=id=>`<svg viewBox="0 0 100 100" aria-hidden="true" fill="#fff3ce" stroke="#514531" stroke-width="4" stroke-linejoin="round" stroke-linecap="round">${bones[id]}</svg>`;
export function mountScience(root,state,save,finish){
 state.phase??='dig';state.cleared??={};state.placed??=[];state.attempts??=0;
 let live=true,selected=null,drag=null,ghost=null,brushing=null,suppressClick=false;
 const clearGesture=()=>{drag=null;brushing=null;selected=null;ghost?.remove();ghost=null;root.querySelectorAll('.fossil-chosen').forEach(n=>n.classList.remove('fossil-chosen'));};
 function render(){
  clearGesture();const found=parts.filter(id=>(state.cleared[id]?.length||0)===6);
  root.innerHTML=`<h2 class="game-instruction">恐龍化石研究所</h2><p class="game-instruction">${state.phase==='dig'?'用手指掃走泥土，搵出四件化石。':state.phase==='assemble'?'睇形狀，將四件化石放返骨架。':'拼好骨架，試下想像恐龍生前嘅外形。'}</p>${state.phase==='dig'?`<div class="fossil-dig" aria-label="四個化石發掘位置">${parts.map(id=>`<div class="fossil-pit" data-pit="${id}">${fossil(id)}<div class="soil-cover">${Array.from({length:6},(_,i)=>`<button data-soil="${id}:${i}" aria-label="掃開${names[id]}位置第 ${i+1} 塊泥" ${state.cleared[id]?.includes(i)?'hidden':''}></button>`).join('')}</div><span>${found.includes(id)?'搵到'+names[id]:'輕輕掃泥'}</span></div>`).join('')}</div><p class="feedback" role="status">已搵到 ${found.length}／4 件化石。可以掃一掃，亦可以逐塊點走泥土。</p><div class="actions"><button class="primary" id="fossil-assemble" ${found.length===4?'':'disabled'}>一齊拼骨架</button></div>`:state.phase==='assemble'?`<div class="fossil-skeleton" aria-label="恐龍骨架拼合位置">${parts.map(id=>`<button class="fossil-slot fossil-${id} ${state.placed.includes(id)?'is-placed':''}" data-slot="${id}" aria-label="${names[id]}位置">${fossil(id)}<span>${state.placed.includes(id)?'✓ ':''}${names[id]}</span></button>`).join('')}</div><div class="choices fossil-tray">${['tail','legs','head','body'].map(id=>`<button class="choice" data-piece="${id}" aria-label="拿起${names[id]}" ${state.placed.includes(id)?'disabled':''}>${fossil(id)}</button>`).join('')}</div><p class="feedback" role="status">${state.attempts>=2?'睇骨頭形狀，同淡色輪廓比一比。':'先點化石，再點位置；亦可以拖過去。'}</p><div class="actions">${hintLevel(state.attempts)==='guided'?'<button id="fossil-help">一齊搵相同形狀</button>':''}<button class="primary" id="fossil-reconstruct" ${state.placed.length===4?'':'disabled'}>睇外形想像</button></div>`:`<div class="fossil-reconstruction"><div class="fossil-mini">${parts.map(fossil).join('')}</div><span aria-hidden="true">→</span><img class="character" src="img/chars/dino-baby.png" alt="根據骨架作出的卡通外形想像"></div><p class="feedback" role="status">呢個係卡通外形想像，唔係恐龍復活。化石幫我哋研究以前嘅生命，認識小龍嘅身體。</p><div class="actions"><button class="primary" id="fossil-finish">完成研究任務</button></div>`}`;
  root.querySelectorAll('[data-soil]').forEach(button=>{button.onclick=()=>sweep(button);button.onpointerdown=e=>{if(e.button!==0||brushing!==null)return;brushing=e.pointerId;root.setPointerCapture(e.pointerId);sweep(button);};});
  root.onpointermove=e=>{if(e.pointerId===brushing)sweep(document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-soil]'));};
  root.onpointerup=()=>{brushing=null;};root.onpointercancel=()=>clearGesture();
  root.querySelector('#fossil-assemble')?.addEventListener('click',()=>{if(!parts.every(id=>state.cleared[id]?.length===6))return;state.phase='assemble';save();render();});
  for(const button of root.querySelectorAll('[data-piece]')){
   const choose=()=>{if(button.disabled)return;selected=button.dataset.piece;root.querySelectorAll('.fossil-chosen').forEach(n=>n.classList.remove('fossil-chosen'));button.classList.add('fossil-chosen');};
   button.onclick=()=>{if(suppressClick){suppressClick=false;return;}choose();};
   button.onpointerdown=e=>{if(e.button!==0||button.disabled||drag)return;suppressClick=false;choose();drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};button.setPointerCapture(e.pointerId);};
   button.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>9){drag.moved=true;if(!ghost){ghost=document.createElement('div');ghost.className='drag-ghost';ghost.innerHTML=fossil(selected);document.body.append(ghost);}ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';}};
   button.onpointerup=e=>{if(!drag||drag.id!==e.pointerId)return;const moved=drag.moved;drag=null;ghost?.remove();ghost=null;if(moved){suppressClick=true;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');if(target&&root.contains(target))place(target.dataset.slot);else clearGesture();}};
   button.onpointercancel=()=>{suppressClick=true;clearGesture();};
  }
  root.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>place(b.dataset.slot));
  root.querySelector('#fossil-help')?.addEventListener('click',()=>{const id=selected||parts.find(id=>!state.placed.includes(id));if(id){root.querySelector(`[data-slot="${id}"]`).classList.add('fossil-hint');root.querySelector(`[data-piece="${id}"]`).classList.add('fossil-hint');}});
  root.querySelector('#fossil-reconstruct')?.addEventListener('click',()=>{if(state.placed.length!==4)return;state.phase='reconstruct';save();render();});
  root.querySelector('#fossil-finish')?.addEventListener('click',()=>{if(live){live=false;finish();}});
 }
 function sweep(button){if(!button||!root.contains(button)||button.hidden)return;const [id,n]=button.dataset.soil.split(':');state.cleared[id]??=[];state.cleared[id].push(Number(n));button.hidden=true;save();const found=parts.filter(id=>state.cleared[id]?.length===6);if(state.cleared[id].length===6)root.querySelector(`[data-pit="${id}"]>span`).textContent='搵到'+names[id];root.querySelector('.feedback').textContent=`已搵到 ${found.length}／4 件化石，輕輕掃，慢慢睇。`;root.querySelector('#fossil-assemble').disabled=found.length!==4;}
 function place(id){if(!selected||state.placed.includes(selected)||state.placed.includes(id))return;if(selected!==id){state.attempts++;save();render();return;}state.placed.push(id);save();render();}
 const background=()=>{if(document.hidden)clearGesture();};document.addEventListener('visibilitychange',background);render();return()=>{live=false;clearGesture();root.onpointermove=null;root.onpointerup=null;root.onpointercancel=null;document.removeEventListener('visibilitychange',background);};
}
