/* 智取恐龍島. School-owned Apps Script. No visitor Google sign-in.
 * Deploy web app execute as owner, allow Anyone if school policy permits.
 * All exposed operations go through dispatch(); helper names end in _. */
var ZONE_IDS_=['chinese','english','mandarin','math','general','science','humanities','art','music','pe','computing'];
var SCORE_TARGET_=10;
var MAX_ZONE_MS_=240000;
var PLAYER_HEADERS_=['id','name','zonesCompleted','zoneIds','totalMs','updatedAt','certReady','version','reachedAt','zones','deviceHash'];
var CERT_HEADERS_=['id','playerId','version','fileId','tokenHash','createdAt','expiresAt','status','deviceHash'];
function props_(){return PropertiesService.getScriptProperties();}
function hash_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s)).map(function(b){return ('0'+((b+256)%256).toString(16)).slice(-2);}).join('');}
var sheetHandles_={};
function sheet_(name){if(!sheetHandles_[name])sheetHandles_[name]=SpreadsheetApp.openById(props_().getProperty('SPREADSHEET_ID')).getSheetByName(name);return sheetHandles_[name];}
function rows_(name){var s=sheet_(name),last=s.getLastRow();return last<2?[]:s.getRange(2,1,last-1,name==='Players'?PLAYER_HEADERS_.length:CERT_HEADERS_.length).getValues();}
function lock_(fn){var l=LockService.getScriptLock();if(!l.tryLock(5000))throw Error('更新繁忙，請稍後再試');try{return fn();}finally{try{SpreadsheetApp.flush();}finally{l.releaseLock();}}}
function device_(token){if(typeof token!=='string'||token.length<24)throw Error('裝置未授權');var h=hash_(token),allowed=JSON.parse(props_().getProperty('DEVICE_HASHES')||'[]');if(allowed.indexOf(h)<0)throw Error('裝置未授權');return h;}
function validId_(s){return typeof s==='string'&&/^[a-zA-Z0-9_-]{8,100}$/.test(s);}
function validatePlayer_(p){if(!p||!validId_(p.id)||!Number.isSafeInteger(p.version)||p.version<1)throw Error('紀錄格式不正確');if(typeof p.name!=='string')throw Error('暱稱不正確');var name=p.name.normalize('NFC').trim();var count=typeof Intl!=='undefined'&&Intl.Segmenter?Array.from(new Intl.Segmenter('zh-HK',{granularity:'grapheme'}).segment(name)).length:Array.from(name).length;if(!name||count>8||/[\u0000-\u001f\u007f\u202a-\u202e\u2066-\u2069]/.test(name))throw Error('暱稱須為一至八個字');if(!p.zones||typeof p.zones!=='object'||Array.isArray(p.zones))throw Error('站點格式不正確');var zones={};Object.keys(p.zones).forEach(function(id){var ms=p.zones[id];if(ZONE_IDS_.indexOf(id)<0||!Number.isSafeInteger(ms)||ms<0||ms>MAX_ZONE_MS_)throw Error('站點時間不正確');zones[id]=ms;});return {id:p.id,name:name,version:p.version,zones:zones};}
function playerFromRow_(r){return {id:r[0],name:JSON.parse(r[1]),zonesCompleted:Number(r[2]),zoneIds:JSON.parse(r[3]),totalMs:Number(r[4]),updatedAt:Number(r[5]),certReady:r[6]===true||r[6]==='TRUE',version:Number(r[7]),reachedAt:Number(r[8])};}
function savePlayer_(data){var deviceHash=device_(data.deviceToken),p=validatePlayer_(data.player);return lock_(function(){var rows=rows_('Players'),index=rows.findIndex(function(r){return r[0]===p.id;}),old=index<0?null:rows[index];if(old&&old[10]!==deviceHash)throw Error('呢份紀錄屬另一部設備');if(old&&p.version<=Number(old[7]))return {acceptedVersion:Number(old[7])};if(old&&JSON.parse(old[1])!==p.name)throw Error('暱稱已鎖定');var zones=old?JSON.parse(old[9]):{};Object.keys(p.zones).forEach(function(id){if(Object.keys(zones).length<SCORE_TARGET_&&!Object.prototype.hasOwnProperty.call(zones,id))zones[id]=p.zones[id];});var chosen=Object.keys(zones).filter(function(id){return ZONE_IDS_.indexOf(id)>=0;}).slice(0,SCORE_TARGET_),limited={};chosen.forEach(function(id){limited[id]=zones[id];});zones=limited;var ids=ZONE_IDS_.filter(function(id){return Object.prototype.hasOwnProperty.call(zones,id);}),total=ids.reduce(function(s,id){return s+zones[id];},0),now=Date.now(),reached=old&&Number(old[2])===SCORE_TARGET_?Number(old[8]):ids.length===SCORE_TARGET_?now:0;var row=[p.id,JSON.stringify(p.name),ids.length,JSON.stringify(ids),total,now,ids.length>=6,p.version,reached,JSON.stringify(zones),deviceHash];sheet_('Players').getRange(index<0?rows.length+2:index+2,1,1,row.length).setValues([row]);return {acceptedVersion:p.version,score:ids.length,totalMs:total};});}
function getBoard_(){var players=rows_('Players').filter(function(r){return r[0];}).map(playerFromRow_);var exploring=players.filter(function(p){return p.zonesCompleted<SCORE_TARGET_;}).length;players=players.filter(function(p){return p.zonesCompleted===SCORE_TARGET_;});players.sort(function(a,b){return a.totalMs-b.totalMs||a.reachedAt-b.reachedAt||a.id.localeCompare(b.id);});return {players:players.slice(0,10),others:Math.max(0,players.length-10),exploring:exploring,serverTime:Date.now()};}
function certToken_(requestId){return Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(requestId,props_().getProperty('CERT_SECRET'))).replace(/=+$/,'');}
function certResult_(row,token){return {url:ScriptApp.getService().getUrl()+'?view=certificate&token='+encodeURIComponent(token),expiresAt:Number(row[6])};}
function uploadCertificate_(data){var deviceHash=device_(data.deviceToken);if(!validId_(data.requestId)||!validId_(data.playerId))throw Error('證書格式不正確');if(typeof data.image!=='string'||!/^data:image\/jpeg;base64,\/9j\//.test(data.image)||data.image.length>4500000)throw Error('請使用小於三MB嘅JPEG證書');var p=rows_('Players').find(function(r){return r[0]===data.playerId;});if(!p||p[10]!==deviceHash||Number(p[2])<6)throw Error('請先同步六站完成紀錄');if(!Number.isSafeInteger(data.version)||data.version<1||data.version>Number(p[7]))throw Error('請先同步最新進度');var token=certToken_(data.requestId),tokenHash=hash_(token),reservation=lock_(function(){var rows=rows_('Certificates'),i=rows.findIndex(function(r){return r[0]===data.requestId;}),r=i<0?null:rows[i];if(r){if(r[1]!==data.playerId||r[8]!==deviceHash)throw Error('證書紀錄不符');if(r[7]==='deleted')throw Error('證書已到期，請重新拍攝');if(r[7]==='ready'){if(Number(r[6])<=Date.now())throw Error('證書已到期，請重新拍攝');return {done:certResult_(r,token)};}if(Date.now()-Number(r[5])<120000)throw Error('證書仍在處理，請稍後再試');}var row=[data.requestId,data.playerId,data.version,'',tokenHash,Date.now(),0,'uploading',deviceHash],index=i<0?rows.length+2:i+2;sheet_('Certificates').getRange(index,1,1,row.length).setValues([row]);return {index:index};});if(reservation.done)return reservation.done;
 var file=null;try{var bytes=Utilities.base64Decode(data.image.split(',')[1]);file=DriveApp.getFolderById(props_().getProperty('FOLDER_ID')).createFile(Utilities.newBlob(bytes,'image/jpeg',data.requestId+'.jpg'));file.setSharing(DriveApp.Access.PRIVATE,DriveApp.Permission.VIEW);var now=Date.now(),row=[data.requestId,data.playerId,data.version,file.getId(),tokenHash,now,now+7*24*60*60*1000,'ready',deviceHash];lock_(function(){sheet_('Certificates').getRange(reservation.index,1,1,row.length).setValues([row]);});return certResult_(row,token);}catch(e){if(file)try{Drive.Files.remove(file.getId());}catch(ignore){}lock_(function(){sheet_('Certificates').getRange(reservation.index,8).setValue('failed');sheet_('Certificates').getRange(reservation.index,6).setValue(0);});throw Error('證書上傳未完成，請重試');}
}
function getCertificate_(token){if(typeof token!=='string'||!/^[\w-]{40,100}$/.test(token))throw Error('下載連結不正確');var h=hash_(token),r=rows_('Certificates').find(function(r){return r[4]===h&&r[7]==='ready';});if(!r||Number(r[6])<=Date.now())throw Error('證書已到期或連結無效');var bytes=DriveApp.getFileById(r[3]).getBlob().getBytes();return {image:'data:image/jpeg;base64,'+Utilities.base64Encode(bytes),expiresAt:Number(r[6])};}
function dispatch(method,payload){switch(method){case'savePlayer':return savePlayer_(payload);case'getBoard':return getBoard_();case'uploadCertificate':return uploadCertificate_(payload);case'getCertificate':return getCertificate_(payload.token);default:throw Error('不支援嘅操作');}}
function doGet(e){var view=e.parameter.view||'certificate';if(view==='bridge'){var allowed=JSON.parse(props_().getProperty('ALLOWED_ORIGINS')||'[]');if(allowed.indexOf(e.parameter.parentOrigin)<0||!validId_(e.parameter.channel))return HtmlService.createHtmlOutput('連線來源未設定');var t=HtmlService.createTemplateFromFile('Bridge');t.origin=JSON.stringify(e.parameter.parentOrigin);t.channel=JSON.stringify(e.parameter.channel);return t.evaluate().setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}var t=HtmlService.createTemplateFromFile('Certificate');t.token=JSON.stringify(/^[\w-]{40,100}$/.test(e.parameter.token||'')?e.parameter.token:'');return t.evaluate().setTitle('智取恐龍島｜領取證書').addMetaTag('viewport','width=device-width, initial-scale=1');}
// Run manually from Apps Script editor once. Result remains in private school sheet.
function setup(){if(props_().getProperty('SPREADSHEET_ID'))throw Error('已設定，唔好重複建立');var ss=SpreadsheetApp.create('智取恐龍島 2026-09-13'),players=ss.getSheets()[0];players.setName('Players');players.appendRow(PLAYER_HEADERS_);players.setFrozenRows(1);var certs=ss.insertSheet('Certificates');certs.appendRow(CERT_HEADERS_);certs.setFrozenRows(1);var tokens=[],hashes=[];for(var i=1;i<=10;i++){var token=Utilities.getUuid()+Utilities.getUuid();tokens.push(['iPad '+i,token]);hashes.push(hash_(token));}var settings=ss.insertSheet('DeviceSetup');settings.appendRow(['設備','私人裝置憑證：只交畀老師']);settings.getRange(2,1,10,2).setValues(tokens);var folder=DriveApp.createFolder('智取恐龍島 私人證書');props_().setProperties({SPREADSHEET_ID:ss.getId(),FOLDER_ID:folder.getId(),DEVICE_HASHES:JSON.stringify(hashes),CERT_SECRET:Utilities.getUuid()+Utilities.getUuid(),ALLOWED_ORIGINS:JSON.stringify(['http://127.0.0.1:4173'])});ScriptApp.newTrigger('cleanupExpired_').timeBased().everyHours(1).create();console.log('設定完成，請到自己雲端硬碟開啟「智取恐龍島 2026-09-13」，並設定 ALLOWED_ORIGINS。');}
function cleanupExpired_(){var now=Date.now(),rows=rows_('Certificates');rows.forEach(function(r,i){if(r[7]==='ready'&&Number(r[6])<=now){try{Drive.Files.remove(r[3]);sheet_('Certificates').getRange(i+2,8).setValue('deleted');}catch(e){console.error('證書清理未完成：'+r[0]);}}});var referenced=new Set(rows.map(function(r){return r[3];}).filter(Boolean)),files=DriveApp.getFolderById(props_().getProperty('FOLDER_ID')).getFiles();while(files.hasNext()){var f=files.next();if(!referenced.has(f.getId())&&now-f.getDateCreated().getTime()>3600000){try{Drive.Files.remove(f.getId());}catch(e){console.error('孤立證書清理未完成');}}}}
