import {playVoice,stopVoice} from '../shared/voice.js';
import {SCHOOL,TITLE,DATE,ZONES,SCORE_TARGET,MAX_ZONE_MS,zoneById,validName,cleanName,nameLength,newPlayer,totals,snapshot,completeZone,ActiveClock,formatTime} from '../shared/core.js';
import {watchOfflineStatus} from '../shared/offline.js';
import {GameClockGate} from '../shared/game-clock-gate.js';
import {icon,escapeHTML} from '../shared/icons.js';
import {read,write,remove,photoStore,DEMO} from '../shared/storage.js';
import {CONFIG} from '../shared/config.js';
import {queuePlayer,flushPlayers,networkSettings} from '../shared/network.js';
import {mountGame} from './games.js';
import {mountParkGuides} from './park-guides.js';
import {mountCertificate} from './certificate.js';
let offlineStatus='正在準備離線遊戲…';
const app=document.querySelector('#app');let player=read('player'),cleanup=()=>{},cert=null,activeZone=null,saveFailed=false;
if(DEMO&&!player){player=newPlayer('示範探險家');write('player',player);}
let toastTimer;function notify(text){document.querySelector('#toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>document.querySelector('#toast').textContent='',4500);}
function persist(){try{if(player)write('player',player);saveFailed=false;}catch{saveFailed=true;notify('本機儲存空間不足，請老師幫手；請勿關閉本頁。');}}
const clock=new ActiveClock(ms=>{if(player&&activeZone&&!player.zones[activeZone]?.complete){const z=player.zones[activeZone];z.ms=Math.min(MAX_ZONE_MS,(z.ms||0)+ms);persist();}});
const clockGate=new GameClockGate(clock);clockGate.setVisible(!document.hidden);
setInterval(()=>clock.checkpoint(),1000);document.addEventListener('visibilitychange',()=>clockGate.setVisible(!document.hidden));window.addEventListener('pagehide',()=>clockGate.setVisible(false));window.addEventListener('pageshow',()=>clockGate.setVisible(!document.hidden));
function synced(){if(!player)return;const snap=snapshot(player);queuePlayer(snap);let archive=read('localBoard',{});archive[player.id]={...snap,...totals(player),reachedAt:Date.now()};write('localBoard',archive);}
function networkLabel(){return !navigator.onLine?'暫時離線，進度存於本機':!networkSettings().appScriptUrl?'進度已存本機':!networkSettings().deviceToken?'未設定裝置憑證，進度只存本機；請老師開設備準備頁。':Object.keys(read('outbox',{})).length?'進度已存本機，等待同步':'進度已同步';}
const brand=()=>`<div class="brand">${CONFIG.schoolLogo?`<img src="${escapeHTML(CONFIG.schoolLogo)}" alt="校徽">`:''}${SCHOOL}</div>`;
function shell(content){app.innerHTML=`<div class="shell"><header class="topbar">${brand()}${DEMO?'<strong>示範試玩 · 不上傳成績</strong>':''}<span class="date">2026 · 09 · 13　開放日</span></header>${content}<footer class="bottom-note"><span class="subtle" id="sync-state">${networkLabel()}</span><span class="subtle" id="offline-state">${escapeHTML(offlineStatus)}</span></footer></div>`;}
function welcome(){shell(`<section class="welcome"><div class="welcome-copy"><p class="eyebrow">小小探險家 · 大大照顧心</p><h1>智取<br>恐龍島</h1><p class="question">點樣照顧恐龍島上嘅小恐龍，令佢哋安全、開心、學識生活？</p><form class="nickname"><label for="nickname">你叫咩暱稱？</label><div class="input-wrap"><input id="nickname" name="nickname" autocomplete="off" placeholder="例如：小晴" aria-describedby="name-help" required><span id="name-count" class="subtle">0／8</span></div><p class="subtle" id="name-help">最多八個字；暱稱會喺現場探險榜出現。</p><button class="primary" type="submit">出發去島上　→</button><p class="subtle">11 關任揀 10 關 · 每關 1 分 · 六分領證</p></form></div><div class="welcome-art"><span class="art-label">一齊照顧小龍！</span><img class="character boy" src="img/chars/xiaozhi-welcome.png" alt="小志張手歡迎"><img class="character dino" src="img/chars/dino-baby.png" alt="綠色小龍"></div></section>`);
 const input=document.querySelector('#nickname');input.addEventListener('input',()=>{let n=nameLength(cleanName(input.value));document.querySelector('#name-count').textContent=n+'／8';input.setCustomValidity(n>8?'暱稱最多八個字。':'');});document.querySelector('form').onsubmit=e=>{e.preventDefault();if(!validName(input.value)){notify('請輸入一至八個字嘅暱稱。');return;}player=newPlayer(input.value);persist();if(saveFailed)return;synced();location.hash='/map';};}
const parkZones=[
 ['山水森林',20,19,34],['動作草原',39,20,34],['招呼村莊',62,19,34],['果樹食堂',83,23,34],
 ['生活花園',17,49,60],['化石山谷',41,49,60],['探險營地',61,48,60],['彩蛋工房',84,49,60],
 ['節奏鼓林',27,76,89],['護蛋草地',52,78,89],['指令基地',77,77,89]
];
function map(){
 const t=totals(player),finished=t.scoreReady;
 shell(`<div class="map-header"><div><p class="map-school">${SCHOOL}</p><h2>智取恐龍島</h2><p>11 個恐龍園區 · 自選 10 關完成挑戰</p></div><div class="progress-label"><span class="map-player">${escapeHTML(player.name)}</span><strong>${t.zonesCompleted}／${SCORE_TARGET}</strong> 分</div></div><div class="map-viewport" role="region" aria-label="恐龍島十一個園區地圖"><div class="map-island"><div class="park-guides" aria-label="小蓮同小志帶你遊恐龍島"><img class="character guide-girl" src="img/chars/xiaolian-welcome.png" alt="導遊小蓮"><img class="character guide-boy" src="img/chars/xiaozhi-step.png" alt="導遊小志"></div>${ZONES.map((z,i)=>{const s=player.zones[z.id],park=parkZones[i],locked=finished&&!s?.complete,status=s?.complete?'✓ 完成 · 1 分':locked?'今次未選':s?'進行中':'';return `<button class="stone ${s?.complete?'done':locked?'locked':s?'active':''}" data-zone="${z.id}" ${s?.complete||locked?'disabled':''} style="left:${park[1]}%;top:${park[2]}%;--label-top:${50+(park[3]-park[2])*4}%" aria-label="${z.name}，${park[0]}，${s?.complete?'已完成，取得一分':locked?'今次未選':s?'繼續照顧':'前往園區'}"><span class="park-label"><strong>${z.name}</strong><span>${park[0]}</span>${status?`<span class="park-status">${status}</span>`:''}</span></button>`;}).join('')}</div></div><p id="guide-status" class="guide-status" role="status">${finished?'10 分滿分！你已完成今次探險。':'撳一個園區，小蓮、小志帶你行過去！'}</p><p class="map-scroll-hint">左右移動地圖，揀你想去嘅園區。</p><div class="bottom-note map-progress"><p class="progress-label">${finished?`10 分滿分！總有效時間 ${formatTime(t.totalMs)}，已取得探險榜排名資格。`:t.certReady?`你已可領證書！再完成 ${SCORE_TARGET-t.zonesCompleted} 關就滿分。`:`再完成 ${6-t.zonesCompleted} 關就有證書`}</p><div class="actions">${t.certReady?'<button class="primary" id="certificate">領證書</button>':''}<button class="quiet" id="next-player">下一位探險家</button></div></div>`);
 document.querySelector('.shell').classList.add('park-page');
 const guides=mountParkGuides(document.querySelector('.map-island'),player,i=>{persist();location.hash='/play/'+ZONES[i].id;});
 cleanup=()=>guides.cleanup();
 document.querySelectorAll('[data-zone]').forEach((b,i)=>b.onclick=()=>guides.walk(i,parkZones[i][0]));
 document.querySelector('#certificate')?.addEventListener('click',()=>location.hash='/cert');
 document.querySelector('#next-player').onclick=nextPlayer;
}
function game(id){const z=zoneById(id),t=totals(player);if(!z){location.hash='/map';return;}if(player.zones[id]?.complete||t.scoreReady){notify(t.scoreReady?'你已經得到 10 分滿分！':'呢一站已完成，請揀其他園區。');location.hash='/map';return;}player.zones[id]??={ms:0,complete:false,game:{}};const saved=player.zones[id];saved.game??={};persist();activeZone=id;const gameLifecycle=clockGate.begin();shell(`<div class="game-top"><button id="back-map">${icon('back')}返地圖</button><h2>${z.name}</h2><button id="game-intro" class="quiet" aria-label="聽玩法">${icon('ear')}聽玩法</button><span class="pill">${t.zonesCompleted}／${SCORE_TARGET} 分</span></div><p class="parent-line"><span>陪伴小貼士</span>${z.parent}</p><section class="game-panel" id="game"></section><div class="game-footer"><span class="care-tag">照顧小龍 · 安全、開心、學識生活</span><span class="subtle">慢慢試，唔使急。</span></div>`);document.querySelector('#back-map').onclick=()=>location.hash='/map';document.querySelector('#game-intro').onclick=()=>{if(document.querySelector('#greeting-stop:not([hidden])')){notify('錄音中，講完先聽玩法。');return;}return playVoice(new URL(`./audio/yue/intro/${id}.wav`,import.meta.url)).then(ok=>{if(!ok)notify('聲音未能播放，可以跟畫面提示繼續。');});};const state=saved.game;cleanup=mountGame(document.querySelector('#game'),z,state,persist,()=>{stopVoice();clockGate.end();completeZone(player,id);persist();synced();cleanup();cleanup=()=>{};const n=document.querySelector('#game');n.innerHTML=`<div class="complete"><p class="eyebrow">照顧任務完成 · 得到 1 分</p><h2>小龍${id==='art'?'開心出蛋啦':id==='music'?'安心啦':'得到你嘅照顧啦'}！</h2><div class="stage">${z.companion?`<img class="character companion" src="img/chars/${z.id==='pe'?'xiaozhi-highfive':z.companion}.png" alt="陪伴同學">`:''}<img class="character companion is-happy" src="img/chars/${'dino-baby'}.png" alt="開心嘅小龍">${id==='math'?'<img class="landmark-greeting" src="img/chars/landmark-triceratops.png" alt="三角龍地標打招呼">':''}</div><p>${z.outcome}</p><button class="primary" id="return-map">返地圖，查看分數</button></div>`;const encouragement=()=>playVoice(new URL('./audio/yue/common/complete.wav',import.meta.url));const intro=document.querySelector('#game-intro');intro.innerHTML=icon('ear')+'聽鼓勵';intro.setAttribute('aria-label','聽鼓勵');intro.onclick=encouragement;encouragement();document.querySelector('#return-map').onclick=()=>location.hash='/map';},gameLifecycle);}
async function nextPlayer(){if(cert?.busy()){notify('證書正在處理，請等完成再換人。');return;}const pending=read('photoPending')===player.id;let dialog=document.createElement('dialog');dialog.innerHTML=`<h2>交畀下一位探險家？</h2><p>${pending?'有相片證書未完成交收。確認換人會放棄本機待傳相片。':'請先確認已保存證書。換人後會清走本機畫面，榜上紀錄仍保留。'}</p><div class="actions"><button id="stay">繼續探索</button><button id="reset" class="primary">${pending?'放棄相片，確認換人':'確認換人'}</button></div>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('#stay').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('#reset').onclick=async()=>{dialog.querySelector('#reset').disabled=true;try{synced();void flushPlayers();await photoStore('delete',player.id);remove('photoPending');remove('lastCertificate');clockGate.end();cleanup();cert?.cleanup();remove('player');player=null;dialog.close();if(location.hash)location.hash='';else render();}catch{notify('本機相片未能清理，請老師幫手，暫時唔換人。');}};}
function render(){stopVoice();if(cert?.busy()){notify('證書正在處理，請留在證書頁。');history.replaceState(null,'','#/cert');return;}clockGate.end();activeZone=null;cleanup();cleanup=()=>{};cert?.cleanup();cert=null;if(!player){if(location.hash)history.replaceState(null,'',location.pathname);welcome();return;}let route=location.hash.slice(1)||'/map';if(route==='/cert'){if(!totals(player).certReady){location.hash='/map';return;}shell(`<div class="game-top"><button id="back-map">${icon('back')}返地圖</button><h2>你嘅照顧證書</h2><button id="next-player" class="quiet">下一位探險家</button></div><section id="certificate"></section>`);document.querySelector('#back-map').onclick=()=>location.hash='/map';document.querySelector('#next-player').onclick=nextPlayer;cert=mountCertificate(document.querySelector('#certificate'),player,notify);}else if(route.startsWith('/play/'))game(route.split('/')[2]);else map();}
window.addEventListener('hashchange',render);window.addEventListener('online',()=>{setTimeout(flushPlayers,Math.random()*15000);updateNetwork();});window.addEventListener('offline',updateNetwork);window.addEventListener('syncstatus',e=>{let n=document.querySelector('#sync-state');if(n)n.textContent=e.detail;});function updateNetwork(){let n=document.querySelector('#sync-state');if(n)n.textContent=networkLabel();}
setTimeout(()=>{flushPlayers();setInterval(flushPlayers,60000);},Math.random()*60000);render();
watchOfflineStatus(status=>{offlineStatus=status;const el=document.querySelector('#offline-state');if(el)el.textContent=status;});
