import {SCHOOL,TITLE,DATE,totals} from '../shared/core.js';
import {photoStore,read,write,remove} from '../shared/storage.js';
import {bridge,networkSettings,flushPlayers} from '../shared/network.js';
import {icon,escapeHTML} from '../shared/icons.js';
import {certificateLink} from '../shared/certificate-link.js';
const image=src=>new Promise((resolve,reject)=>{let i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('證書圖片未能載入，請重試'));i.src=src;});
function fit(ctx,img,x,y,w,h,cover=false){const s=cover?Math.max(w/img.width,h/img.height):Math.min(w/img.width,h/img.height);ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.drawImage(img,x+(w-img.width*s)/2,y+(h-img.height*s)/2,img.width*s,img.height*s);ctx.restore();}
export async function makeCertificate(player,photo=null){const c=document.createElement('canvas');c.width=1600;c.height=2000;const ctx=c.getContext('2d');ctx.fillStyle='#f6f3ec';ctx.fillRect(0,0,1600,2000);ctx.strokeStyle='#b8923a';ctx.lineWidth=12;ctx.strokeRect(55,55,1490,1890);ctx.lineWidth=3;ctx.strokeRect(80,80,1440,1840);ctx.textAlign='center';ctx.fillStyle='#146b4d';const text=(s,y,size,weight=700)=>{ctx.fillStyle='#146b4d';ctx.font=`${weight} ${size}px "PingFang HK","Microsoft JhengHei",sans-serif`;ctx.fillText(s,800,y,1390);};text(SCHOOL,170,48);text(TITLE,290,100);text('恐龍島照顧任務證書',380,46);if(photo){let p=await image(photo);ctx.fillStyle='#e7eddc';ctx.fillRect(280,440,1040,820);fit(ctx,p,290,450,1020,800,true);}else{ctx.fillStyle='#e7eddc';ctx.beginPath();ctx.ellipse(800,820,510,340,0,0,Math.PI*2);ctx.fill();text('安全 · 開心 · 學識生活',720,52);text('多謝你用心照顧小龍',820,50);}
 const border=await image('img/ui/cert-frame.png');ctx.save();ctx.globalAlpha=.5;ctx.drawImage(border,30,30,1540,1940);ctx.restore();const [girl,boy,dino]=await Promise.all(['xiaolian-highfive','xiaozhi-highfive','dino-baby'].map(n=>image('img/chars/'+n+'.png')));fit(ctx,girl,365,940,470,500);ctx.save();ctx.translate(1600,0);ctx.scale(-1,1);fit(ctx,boy,365,940,470,500);ctx.restore();fit(ctx,dino,660,1200,280,240);text(player.name,1530,82);text('完成恐龍島照顧任務',1625,52);text(`${totals(player).zonesCompleted}／10 分`,1740,84);text(DATE,1850,40);return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('證書未能產生')),'image/jpeg',.88));}
const dataURL=blob=>new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});
export function mountCertificate(root,player,notify){let live=true,stream=null,photo=null,blob=null,previewURL=null,previewVersion=0,busy=false,processing=false,uploading=false,pending=null,timers=[];
 root.innerHTML=`<div class="cert-layout"><div><img class="cert-preview" alt="個人照顧任務證書預覽"><p class="subtle" style="text-align:center;margin-top:10px">${totals(player).zonesCompleted}／10 分 · ${DATE}</p></div><div class="cert-controls"><h2>留低呢份開心</h2><p>普通證書可以直接儲存。想同小蓮、小志、小龍合照，請家長幫手拍一張。</p><div class="actions"><button class="primary" id="camera-start">${icon('camera','small-icon')} 拍照證書</button><button id="save-local" disabled>儲存普通證書</button></div><div class="notice">拍照由家長自選；確認後上傳合成證書，供持有下載連結者領取。相片唔上探險榜，連結有效 7 日。到期即停止下載，雲端圖片由排程清理。</div><div id="camera-area" class="hidden"><video class="camera-view" autoplay muted playsinline></video><p id="camera-count" role="status"></p><div class="actions"><button id="shutter" class="gold">準備好，影相</button><button id="camera-cancel">取消拍照</button></div></div><div id="photo-actions" class="hidden"><div class="actions"><button id="upload" class="primary">確認並產生下載碼</button><button id="retake">重拍</button><button id="discard">改用普通證書</button></div></div><p id="cert-status" role="status" aria-live="polite">正在製作證書…</p><div id="qr" class="hidden qr-wrap"></div></div></div>`;
 const $=s=>root.querySelector(s),status=s=>{if(live)$('#cert-status').textContent=s;};
 const stop=()=>{busy=false;stream?.getTracks().forEach(t=>t.stop());stream=null;timers.forEach(clearTimeout);timers=[];};
 async function preview(){const version=++previewVersion;blob=null;$('#save-local').disabled=true;$('#upload').disabled=true;try{let next=await makeCertificate(player,photo);if(!live||version!==previewVersion)return;blob=next;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(blob);$('.cert-preview').src=previewURL;$('#save-local').disabled=false;$('#upload').disabled=false;$('#save-local').textContent=photo?'儲存相片證書':'儲存普通證書';status(photo?'先睇清楚相片，確認先上傳。':'證書準備好，可以儲存。');}catch(e){if(live&&version===previewVersion)status(e.message);}}
 function hideQR(){$('#qr').classList.add('hidden');$('#qr').replaceChildren();}
 async function startCamera(){if(uploading)return;stop();hideQR();status('請允許使用相機。');try{let s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:960}},audio:false});if(!live){s.getTracks().forEach(t=>t.stop());return;}stream=s;$('#camera-area').classList.remove('hidden');$('#photo-actions').classList.add('hidden');$('video').srcObject=stream;await $('video').play();$('#shutter').disabled=false;$('#camera-count').textContent='';status('請家長幫手對準，避開其他來賓。');}catch{status('未能開啟相機，仍可儲存普通證書。');}}
 async function discard(){if(uploading)return;stop();photo=null;pending=null;write('photoPending',null);await photoStore('delete',player.id);$('#camera-area').classList.add('hidden');$('#photo-actions').classList.add('hidden');hideQR();preview();}
 async function showQR(result){const link=certificateLink(result,networkSettings().appScriptUrl);let qr=window.qrcode(0,'M');qr.addData(link);qr.make();$('#qr').innerHTML=qr.createSvgTag({cellSize:5,margin:4,scalable:true})+`<p><strong>家長掃碼，儲存證書</strong></p><p>有效至 ${escapeHTML(new Date(result.expiresAt).toLocaleString('zh-HK',{timeZone:'Asia/Hong_Kong'}))}</p><p class="subtle">請先確認手機開到證書，再交畀下一位。</p>`;$('#qr').classList.remove('hidden');status('證書已上傳，可以掃碼下載。');}
 async function upload(){if(uploading||!blob)return;const settings=networkSettings();if(!settings.appScriptUrl||!settings.deviceToken){status('活動相片連線尚未設定；可以先儲存本機證書。');return;}if(!navigator.onLine){status('暫時離線，相片留在本機；連線後再按確認。');return;}uploading=true;$('#upload').disabled=true;$('#retake').disabled=true;$('#discard').disabled=true;$('#camera-start').disabled=true;
 try{status('先確認完成紀錄，請稍候…');if(!await flushPlayers())throw Error('完成紀錄仍在同步，請稍後再試');if(!pending){pending={requestId:crypto.randomUUID(),playerId:player.id,version:player.version,blob};await photoStore('put',player.id,pending);write('photoPending',player.id);}status('正在上傳證書，請稍候…');const url=await dataURL(pending.blob);const result=await bridge.call('uploadCertificate',{deviceToken:settings.deviceToken,playerId:player.id,version:pending.version,requestId:pending.requestId,image:url},60000);certificateLink(result,settings.appScriptUrl);write('lastCertificate',{playerId:player.id,version:pending.version,result});await photoStore('delete',player.id);write('photoPending',null);if(live)await showQR(result);
 }catch(e){status(e.message+'；相片仍在本機，可以重試。');}finally{uploading=false;if(live){$('#upload').disabled=false;$('#retake').disabled=false;$('#discard').disabled=false;$('#camera-start').disabled=false;}}
 }
 $('#camera-start').onclick=startCamera;$('#retake').onclick=startCamera;$('#camera-cancel').onclick=()=>{stop();$('#camera-area').classList.add('hidden');if(photo)$('#photo-actions').classList.remove('hidden');status('已關閉相機。');};$('#discard').onclick=discard;
 $('#shutter').onclick=()=>{if(busy)return;busy=true;$('#shutter').disabled=true;let n=3;const tick=async()=>{if(!live){busy=false;return;}$('#camera-count').textContent=String(n);if(n-->0){timers.push(setTimeout(tick,1000));return;}const video=$('video');if(!video.videoWidth){busy=false;$('#shutter').disabled=false;status('鏡頭未準備好，請再試。');return;}processing=true;const c=document.createElement('canvas');c.width=1280;c.height=960;const ctx=c.getContext('2d');ctx.translate(1280,0);ctx.scale(-1,1);const vw=video.videoWidth,vh=video.videoHeight,scale=Math.max(1280/vw,960/vh);ctx.drawImage(video,(1280-vw*scale)/2,(960-vh*scale)/2,vw*scale,vh*scale);photo=c.toDataURL('image/jpeg',.85);stop();busy=false;pending=null;await photoStore('delete',player.id);write('photoPending',player.id);$('#camera-area').classList.add('hidden');$('#photo-actions').classList.remove('hidden');await preview();if(live&&blob){pending={requestId:crypto.randomUUID(),playerId:player.id,version:player.version,blob};await photoStore('put',player.id,pending);}processing=false;};tick();};
 $('#save-local').onclick=async()=>{if(!blob)return;let f=new File([blob],'恐龍島照顧證書.jpg',{type:'image/jpeg'});try{if(navigator.canShare?.({files:[f]})){await navigator.share({files:[f],title:'恐龍島照顧證書'});return;}}catch(e){if(e.name==='AbortError')return;}const a=document.createElement('a');a.href=previewURL;a.download='恐龍島照顧證書.jpg';a.click();notify('若未見下載，可長按證書圖片儲存。');};$('#upload').onclick=upload;
 (async()=>{try{const saved=await photoStore('get',player.id);if(!live)return;if(saved){pending=saved;blob=saved.blob;previewURL=URL.createObjectURL(blob);$('.cert-preview').src=previewURL;$('#save-local').disabled=false;$('#save-local').textContent='儲存相片證書';$('#photo-actions').classList.remove('hidden');status('有一張待傳證書，可以確認上傳或改用普通證書。');return;}await preview();let last=read('lastCertificate');if(last?.playerId===player.id&&last.version===player.version&&last.result.expiresAt>Date.now()&&live)await showQR(last.result);}catch(e){status('本機相片未能讀取，請使用普通證書。');await preview();}})();
 return {cleanup(){live=false;stop();if(previewURL)URL.revokeObjectURL(previewURL);},busy:()=>uploading||processing};
}
